import { User } from "@/types/user";

export const EXAMPLE_USERS: User[] = [
  {
    id: "1",
    full_name: "Alice Johnson",
    email: "alice@gdsc.com",
    role: "USER",
    position: 1,
    branch: 1,
    github: "https://github.com/alicejohnson",
    linkedin: "https://linkedin.com/in/alicejohnson",
    tags: ["frontend", "typescript"],
    bio: "Passionate frontend developer and community builder.",
    is_onboarded: true,
    graduation_date: new Date("2025-06-15"),
  },
  {
    id: "2",
    full_name: "Bob Smith",
    email: "bob@gdsc.com",
    role: "USER",
    position: 1,
    branch: 1,
    github: "https://github.com/bobsmith",
    linkedin: "https://linkedin.com/in/bobsmith",
    tags: ["backend", "go", "devops"],
    bio: "Former GDSC backend lead, now working in DevOps.",
    is_onboarded: true,
    graduation_date: new Date("2023-05-10"),
  },
  {
    id: "3",
    full_name: "Catherine Liu",
    email: "catherine@gdsc.com",
    role: "USER",
    position: 1,
    branch: 1,
    twitter: "https://twitter.com/catherineliu",
    tags: ["design", "mentorship", "branding"],
    bio: "Helping the next generation of tech leaders shine.",
    is_onboarded: true,
  },
  {
    id: "4",
    full_name: "Daniel Martinez",
    email: "daniel@gdsc.com",
    role: "ADMIN",
    position: 1,
    branch: 1,
    github: "https://github.com/danielm",
    linkedin: "https://linkedin.com/in/danielm",
    instagram: "https://instagram.com/danielcodes",
    tags: ["fullstack", "firebase", "leadership"],
    bio: "Leading with code and compassion.",
    is_onboarded: true,
    graduation_date: new Date("2024-12-20"),
  },
  {
    id: "5",
    full_name: "Emily Nguyen",
    email: "emily@gdsc.com",
    role: "USER",
    position: 1,
    branch: 1,
    tags: ["career", "networking", "education"],
    bio: "Tech advisor and career coach for student developers.",
    is_onboarded: false,
  },
];
